channels:
  - conda-forge
dependencies:
  - expat
  - gdal
  - git
  - gmp
  - jupyter
  - mpfr
  - nbgitpuller
  - proj
  - udunits2
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-sf
  - r-tidyverse
  - pip:
    - nbconvert[webpdf]
